### ISSUE TITLE
User who creates a group is the admin of the group.

### ISSUE THREAD

**Issue by minju25kim** [fac24/StreetCred#1]
- Admin can remove items and members from a group.

**Comment by minju25kim** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [User who creates a group is the admin of the group.](https://trello.com/c/LkEyMhzS/5-user-who-creates-a-group-is-the-admin-of-the-group)

**Comment by AsmahanM** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test card](https://trello.com/c/OfSJoCug/56-test-card)

**Comment by sonianb** [comment]
Closed by #20
